elliepass:
  elliepass_enabled:
    default: false
    client: true

  elliepass_api_url:
    default: "https://elliepass.com"

  elliepass_community_key:
    default: ""

  elliepass_community_secret:
    default: ""
    secret: true
  
  elliepass_durable_cache_hours:
    default: 720
    min: 1
    max: 8760
    hidden: true

  elliepass_location_cache_hours:
    default: 24
    min: 1
    max: 168
    hidden: true

  elliepass_debug_logging:
    default: false
    client: false
  